server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost/powerup
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}
  token.admin : eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFpbEBzb21lLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWRVc2VyIjoxLCJpYXQiOjE2ODY0OTk2MjgsImV4cCI6OTIyMzM3MjAzNjg1NDc3NX0.BjqCzQ7ZuoQbrjmTnxxHYjxzsfeKjR9-VWW4l8-pOi4GWFT2tb6xKJ9EVYCJvfL_Tt3dPMWdjXCEvsPOlATNaA

management:
  endpoints:
    web:
      exposure:
        include: "*"